import assert from "node:assert/strict";
import test from "node:test";
import { UNIT_1_EXERCISES } from "../src/data/physics/unit-1/exercises.js";
import { UNIT_1_EXERCISE_FAMILIES } from "../src/data/physics/unit-1/families.js";
import { UNIT_2_EXERCISES } from "../src/data/physics/unit-2/exercises.js";
import { UNIT_2_EXERCISE_FAMILIES } from "../src/data/physics/unit-2/families.js";
import { UNIT_3_CONTENT } from "../src/data/physics/unit-3/content.js";
import { UNIT_3_COMMON_ERRORS } from "../src/data/physics/unit-3/common-errors.js";
import { UNIT_3_VISUALIZATIONS } from "../src/data/physics/unit-3/visualizations.js";
import { UNIT_3_EXERCISES } from "../src/data/physics/unit-3/exercises.js";
import { UNIT_3_EXERCISE_FAMILIES } from "../src/data/physics/unit-3/families.js";
import { generateLocalizedUnit3FamilyInstance, getLocalizedUnit3Exercises } from "../src/data/physics/unit-3/exercise-localize.js";
import { gradeExerciseResponse } from "../src/utils/bonus.js";
import { generateFamilyInstance, validateFamilyDefinition } from "../src/utils/exercise-families.js";

const seededRandom=(seed)=>{let state=seed>>>0;return()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/0x1_0000_0000;};};
const finite=(value,seen=new WeakSet())=>{if(typeof value==="number")return Number.isFinite(value);if(!value||typeof value!=="object")return true;if(seen.has(value))return true;seen.add(value);return Object.values(value).every((child)=>finite(child,seen));};
const interactionInvariant=(interaction)=>interaction.kind==="singleChoice"?{kind:interaction.kind,optionIds:interaction.options.map(({id})=>id),correctOptionId:interaction.correctOptionId}:{kind:interaction.kind,fields:(interaction.kind==="number"?[interaction.field]:interaction.fields).map(({id,unit})=>({id,unit}))};
const invariant=(exercise)=>({id:exercise.id,unit:exercise.unit,topic:exercise.topic,subtopic:exercise.subtopic,type:exercise.type,representation:exercise.representation,cognitiveLevel:exercise.cognitiveLevel,difficulty:exercise.difficulty,modalities:exercise.modalities,answer:Object.fromEntries(Object.entries(exercise.answer).filter(([key])=>!["display","presentation"].includes(key))),tolerance:exercise.tolerance,expectedUnit:exercise.expectedUnit,bonusEligible:exercise.bonusEligible,commonErrors:exercise.commonErrors,purpose:exercise.purpose,exposure:exercise.exposure,status:exercise.status,interaction:interactionInvariant(exercise.interaction)});
const gradeSummary=({answered,correct,pointsEarned,pointsPossible,fieldResults})=>({answered,correct,pointsEarned,pointsPossible,fieldResults});

test("el banco fijo contiene exactamente 36 ejercicios con la distribución acordada",()=>{assert.equal(UNIT_3_EXERCISES.length,36);assert.equal(new Set(UNIT_3_EXERCISES.map(({id})=>id)).size,36);assert.ok(UNIT_3_EXERCISES.every(({id,unit,bonusEligible})=>id.startsWith("u3-")&&unit===3&&bonusEligible===false));assert.deepEqual(Object.fromEntries(Object.keys(UNIT_3_CONTENT).map((topic)=>[topic,UNIT_3_EXERCISES.filter((exercise)=>exercise.topic===topic).length])),{equilibrio:4,"dinamica-particulas":5,"fuerza-normal":4,tension:4,friccion:6,"resistencia-fluidos":4,"dinamica-circular":6,"fuerzas-fundamentales":3});});

test("los ejercicios resuelven taxonomía, visualizaciones, errores e interacciones",()=>{const errors=new Set(UNIT_3_COMMON_ERRORS.map(({id})=>id));for(const exercise of UNIT_3_EXERCISES){assert.ok(UNIT_3_CONTENT[exercise.topic]?.sections.some(({id})=>id===exercise.subtopic),exercise.id);assert.ok(exercise.title&&exercise.prompt&&exercise.objectives.length&&exercise.hints.length&&exercise.solution.length,exercise.id);assert.ok(exercise.commonErrors.every((id)=>errors.has(id)),exercise.id);if(exercise.visualizationId)assert.ok(UNIT_3_VISUALIZATIONS[exercise.visualizationId],exercise.id);if(exercise.interaction.kind==="singleChoice")assert.deepEqual(exercise.interaction.options.map(({id})=>id),["a","b","c","d"],exercise.id);else{assert.ok(exercise.expectedUnit,exercise.id);const tolerances=typeof exercise.tolerance==="object"?Object.values(exercise.tolerance):[exercise.tolerance];assert.ok(tolerances.every((value)=>Number.isFinite(value)&&value>=0),exercise.id);const input=exercise.answer.kind==="number"?String(exercise.answer.value):exercise.answer.values.map(({value})=>String(value));assert.equal(gradeExerciseResponse(exercise,input).correct,true,exercise.id);}}});

test("los 36 ejercicios tienen presentación inglesa completa y grading invariante",()=>{const es=getLocalizedUnit3Exercises("es"),en=getLocalizedUnit3Exercises("en");assert.deepEqual(en.map(invariant),es.map(invariant));en.forEach((exercise,index)=>{assert.notEqual(exercise.title,es[index].title,exercise.id);assert.notEqual(exercise.prompt,es[index].prompt,exercise.id);assert.equal(exercise.solution.length,es[index].solution.length,exercise.id);const input=exercise.interaction.kind==="singleChoice"?exercise.interaction.correctOptionId:exercise.answer.kind==="number"?String(exercise.answer.value):exercise.answer.values.map(({value})=>String(value));assert.deepEqual(gradeSummary(gradeExerciseResponse(exercise,input)),gradeSummary(gradeExerciseResponse(es[index],input)),exercise.id);});});

test("las diez familias generan mil estados deterministas y físicamente válidos",()=>{assert.equal(UNIT_3_EXERCISE_FAMILIES.length,10);assert.equal(new Set(UNIT_3_EXERCISE_FAMILIES.map(({id})=>id)).size,10);for(const [familyIndex,family] of UNIT_3_EXERCISE_FAMILIES.entries()){assert.equal(validateFamilyDefinition(family).valid,true,family.id);assert.match(family.id,/^u3-family-/);assert.equal(family.unit,3);assert.equal(family.bonusEligible,false);for(let seed=1;seed<=100;seed+=1){const first=generateFamilyInstance(family,{random:seededRandom(seed*101+familyIndex)}),second=generateFamilyInstance(family,{random:seededRandom(seed*101+familyIndex)});assert.equal(finite(first.parameters)&&finite(first.answer),true,`${family.id}:${seed}`);assert.deepEqual(first.parameters,second.parameters);assert.deepEqual(first.answer,second.answer);assert.deepEqual(interactionInvariant(first.interaction),interactionInvariant(second.interaction));const p=first.parameters,a=first.answer;if(family.id==="u3-family-equilibrium-vector"){assert.equal(p.F1x+p.F2x+a.values[0].value,0);assert.equal(p.F1y+p.F2y+a.values[1].value,0);}if(family.id==="u3-family-elevator-normal")assert.ok(Math.abs(a.value-p.m*(p.g+p.ay))<0.001);if(family.id==="u3-family-atwood")assert.ok(a.values[0].value>0&&a.values[0].value<p.g);if(family.id==="u3-family-static-friction-test")assert.ok(Math.abs(p.F-p.mu*p.m*p.g)>=1);if(family.id==="u3-family-kinetic-horizontal")assert.ok(Math.abs(a.value-(p.F-p.mu*p.m*p.g)/p.m)<0.002);if(family.id==="u3-family-terminal-linear")assert.ok(Math.abs(p.m*p.g-p.b*a.value)<0.01);if(family.id==="u3-family-terminal-quadratic")assert.ok(Math.abs(p.m*p.g-p.c*a.value*a.value)<0.01);if(family.id==="u3-family-flat-curve")assert.ok(Math.abs(p.mu*p.g-pow(a.value,2)/p.R)<0.001);if(family.id==="u3-family-vertical-circle-bottom")assert.ok(Math.abs((a.value-p.m*p.g)-p.m*p.v*p.v/p.R)<0.001);}}});
const pow=(value,exponent)=>value**exponent;

test("la misma seed conserva estado físico y grading entre ES y EN en las diez familias",()=>{for(const [index,family] of UNIT_3_EXERCISE_FAMILIES.entries())for(const seed of [7,41,2026,9001]){const es=generateLocalizedUnit3FamilyInstance(family,"es",{random:seededRandom(seed+index)}),en=generateLocalizedUnit3FamilyInstance(family,"en",{random:seededRandom(seed+index)});assert.deepEqual(en.parameters,es.parameters,family.id);assert.deepEqual(invariant(en),invariant(es),family.id);assert.notEqual(en.title,es.title,family.id);const input=es.interaction.kind==="singleChoice"?es.interaction.correctOptionId:es.answer.kind==="number"?String(es.answer.value):es.answer.values.map(({value})=>String(value));assert.deepEqual(gradeSummary(gradeExerciseResponse(en,input)),gradeSummary(gradeExerciseResponse(es,input)),family.id);}});

test("la publicación de Unidad 3 no altera los bancos anteriores ni crea Bonos",()=>{assert.equal(UNIT_1_EXERCISES.length,55);assert.equal(UNIT_1_EXERCISE_FAMILIES.length,15);assert.equal(UNIT_2_EXERCISES.length,41);assert.equal(UNIT_2_EXERCISE_FAMILIES.length,8);assert.ok(UNIT_3_EXERCISES.every(({modalities})=>!modalities.includes("bonus")));});
