import assert from "node:assert/strict";
import test from "node:test";
import { UNIT_7_CONTENT } from "../src/data/physics/unit-7/content.js";
import { UNIT_7_EXERCISES } from "../src/data/physics/unit-7/exercises.js";
import { UNIT_7_EXERCISE_FAMILIES } from "../src/data/physics/unit-7/families.js";
import { generateLocalizedUnit7FamilyInstance,getLocalizedUnit7Exercises } from "../src/data/physics/unit-7/exercise-localize.js";
import { localizeAcademicUnitLabel } from "../src/data/physics/localize-unit-label.js";
import { gradeExerciseResponse } from "../src/utils/bonus.js";
import { generateFamilyInstance,roundTo,validateFamilyDefinition } from "../src/utils/exercise-families.js";
const seededRandom=(seed)=>{let state=seed>>>0;return()=>{state=(Math.imul(state,1664525)+1013904223)>>>0;return state/0x1_0000_0000;};};
const finite=(value,seen=new WeakSet())=>{if(typeof value==="number")return Number.isFinite(value);if(!value||typeof value!=="object")return true;if(seen.has(value))return true;seen.add(value);return Object.values(value).every((child)=>finite(child,seen));};
const invariant=(exercise)=>({id:exercise.id,unit:exercise.unit,topic:exercise.topic,subtopic:exercise.subtopic,type:exercise.type,answer:Object.fromEntries(Object.entries(exercise.answer).filter(([key])=>!["display","presentation"].includes(key))),tolerance:exercise.tolerance,expectedUnit:exercise.expectedUnit,bonusEligible:exercise.bonusEligible,interaction:exercise.interaction.kind==="singleChoice"?{kind:"singleChoice",ids:exercise.interaction.options.map(({id})=>id),correctOptionId:exercise.interaction.correctOptionId}:{kind:exercise.interaction.kind,fields:(exercise.interaction.kind==="number"?[exercise.interaction.field]:exercise.interaction.fields).map(({id,unit})=>({id,unit}))}});
const selectedRandom=(...selections)=>{let index=0;return()=>{const [choice,length]=selections[index++];return(choice+0.25)/length;};};
test("el banco fijo contiene exactamente 40 ejercicios válidos y sin Bonos",()=>{assert.equal(UNIT_7_EXERCISES.length,40);assert.equal(new Set(UNIT_7_EXERCISES.map(({id})=>id)).size,40);assert.ok(UNIT_7_EXERCISES.every(({id,unit,bonusEligible,modalities,topic,subtopic})=>id.startsWith("u7-")&&unit===7&&!bonusEligible&&!modalities.includes("bonus")&&UNIT_7_CONTENT[topic]?.sections.some(({id})=>id===subtopic)));for(const exercise of UNIT_7_EXERCISES){assert.ok(exercise.title&&exercise.prompt&&exercise.solution.length);const input=exercise.interaction.kind==="singleChoice"?exercise.interaction.correctOptionId:String(exercise.answer.value);assert.equal(gradeExerciseResponse(exercise,input).correct,true,exercise.id);}});
test("los 40 ejercicios conservan datos y grading entre ES y EN",()=>{const es=getLocalizedUnit7Exercises("es"),en=getLocalizedUnit7Exercises("en");assert.deepEqual(en.map(invariant),es.map(invariant));en.forEach((exercise,index)=>{assert.notEqual(exercise.title,es[index].title);assert.notEqual(exercise.prompt,es[index].prompt);const input=exercise.interaction.kind==="singleChoice"?exercise.interaction.correctOptionId:String(exercise.answer.value);assert.equal(gradeExerciseResponse(exercise,input).correct,true,exercise.id);});});
test("las doce familias son deterministas, finitas y respetan invariantes físicos",()=>{assert.equal(UNIT_7_EXERCISE_FAMILIES.length,12);assert.equal(new Set(UNIT_7_EXERCISE_FAMILIES.map(({id})=>id)).size,12);for(const [index,family] of UNIT_7_EXERCISE_FAMILIES.entries()){assert.equal(validateFamilyDefinition(family).valid,true,family.id);assert.equal(family.unit,7);assert.equal(family.bonusEligible,false);for(let seed=1;seed<=100;seed++){const first=generateFamilyInstance(family,{random:seededRandom(seed*109+index)}),second=generateFamilyInstance(family,{random:seededRandom(seed*109+index)});assert.deepEqual(first.parameters,second.parameters);assert.deepEqual(first.answer,second.answer);assert.ok(finite(first),family.id);const p=first.parameters;if(family.id==="u7-family-circular-orbit"){const orbit=Math.sqrt(p.mu/p.radius),escape=Math.sqrt(2*p.mu/p.radius);assert.ok(Math.abs(escape/Math.SQRT2-orbit)<1e-9);}if(family.id==="u7-family-shm-energy"){const values=first.answer.values;assert.ok(values[2].value>=-1e-9&&Math.abs(p.position)<=p.amplitude);}if(family.id==="u7-family-damped-oscillator"){const gamma=p.damping/(2*p.mass),omega0=Math.sqrt(p.spring/p.mass);assert.ok(gamma<omega0);assert.ok(omega0**2-gamma**2>0);assert.ok(first.answer.values[3].value<=p.amplitude+1e-9);}if(family.id==="u7-family-driven-response"){assert.ok(p.damping>0);assert.ok(Number.isFinite(first.answer.value));assert.ok(Math.sqrt((p.spring-p.mass*p.drive**2)**2+(p.damping*p.drive)**2)>0);}}}});
test("las familias localizadas conservan parámetros y respuestas",()=>{for(const [index,family] of UNIT_7_EXERCISE_FAMILIES.entries())for(const seed of [7,41,2026]){const es=generateLocalizedUnit7FamilyInstance(family,"es",{random:seededRandom(seed+index)}),en=generateLocalizedUnit7FamilyInstance(family,"en",{random:seededRandom(seed+index)});assert.deepEqual(en.parameters,es.parameters);assert.deepEqual(invariant(en).answer,invariant(es).answer);assert.notEqual(en.title,es.title);}});

test("los 63 estados del MAS se calculan desde la fase sin reutilizar x redondeada",()=>{const family=UNIT_7_EXERCISE_FAMILIES.find(({id})=>id==="u7-family-shm-state"),amplitudes=[0.05,0.1,0.2],omegas=[2,5,10],phases=[0,Math.PI/6,Math.PI/4,Math.PI/3,Math.PI/2,Math.PI,3*Math.PI/2];let count=0;for(const [ai,amplitude] of amplitudes.entries())for(const [oi,omega] of omegas.entries())for(const [pi,phase] of phases.entries()){const instance=generateFamilyInstance(family,{random:selectedRandom([ai,amplitudes.length],[oi,omegas.length],[pi,phases.length])}),exact=[amplitude*Math.cos(phase),-amplitude*omega*Math.sin(phase),-(omega**2)*amplitude*Math.cos(phase)];instance.answer.values.forEach(({value},index)=>assert.ok(Math.abs(value-exact[index])<=instance.tolerance,`${amplitude}:${omega}:${phase}:${index}`));const response=exact.map((value)=>String(roundTo(value)));assert.equal(gradeExerciseResponse(instance,response).correct,true,`${amplitude}:${omega}:${phase}`);count++;}assert.equal(count,63);const regression=generateFamilyInstance(family,{random:selectedRandom([1,3],[2,3],[1,7])});assert.equal(regression.answer.values[2].value,-8.66);});

test("las 160 variantes de gravedad-altura, incluidas las 80 de peso, usan el campo sin redondear",()=>{const family=UNIT_7_EXERCISE_FAMILIES.find(({id})=>id==="u7-family-gravity-altitude"),fields=[3.7,8,9.8,11],ratios=[0,0.25,0.5,1,2],masses=[10,40,70,100],variants=["field","weight"];let count=0,weightCount=0;for(const [gi,g0] of fields.entries())for(const [hi,heightRatio] of ratios.entries())for(const [mi,mass] of masses.entries())for(const [vi,variant] of variants.entries()){const instance=generateFamilyInstance(family,{random:selectedRandom([gi,fields.length],[hi,ratios.length],[mi,masses.length],[vi,variants.length])}),fieldRaw=g0/(1+heightRatio)**2,exact=variant==="field"?fieldRaw:mass*fieldRaw;assert.ok(Math.abs(instance.answer.value-exact)<=instance.tolerance,`${g0}:${heightRatio}:${mass}:${variant}`);assert.equal(gradeExerciseResponse(instance,String(roundTo(exact))).correct,true,`${g0}:${heightRatio}:${mass}:${variant}`);count++;if(variant==="weight")weightCount++;}assert.equal(count,160);assert.equal(weightCount,80);const regression=generateFamilyInstance(family,{random:selectedRandom([1,4],[2,5],[3,4],[1,2])});assert.equal(regression.answer.value,355.556);});

test("las unidades visibles de familias inglesas pasan por la localización académica compartida",()=>{for(const [index,family] of UNIT_7_EXERCISE_FAMILIES.entries())for(const seed of [1,7,41,2026]){const es=generateLocalizedUnit7FamilyInstance(family,"es",{random:seededRandom(seed+index)}),en=generateLocalizedUnit7FamilyInstance(family,"en",{random:seededRandom(seed+index)}),esFields=es.interaction.kind==="number"?[es.interaction.field]:es.interaction.fields,enFields=en.interaction.kind==="number"?[en.interaction.field]:en.interaction.fields;assert.equal(en.expectedUnit,es.expectedUnit,family.id);assert.deepEqual(enFields.map(({unitLabel})=>unitLabel),esFields.map(({unitLabel,unit})=>localizeAcademicUnitLabel(unitLabel??unit,"en")),family.id);assert.doesNotMatch(JSON.stringify({fields:enFields.map(({unitLabel})=>unitLabel),display:en.answer.display}),/adimensional|sin unidad/i,family.id);}const family=UNIT_7_EXERCISE_FAMILIES.find(({id})=>id==="u7-family-kepler-scaling"),es=generateLocalizedUnit7FamilyInstance(family,"es",{random:()=>0}),en=generateLocalizedUnit7FamilyInstance(family,"en",{random:()=>0});assert.equal(es.interaction.field.unit,"adimensional");assert.equal(en.interaction.field.unit,"adimensional");assert.equal(en.interaction.field.unitLabel,"dimensionless");assert.match(en.answer.display,/dimensionless/);});
